services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo_volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network
    restart: always

volumes:
  mongo_volume:

networks:
  my_network: